### ISSUE TITLE
导出csv出现乱码

### ISSUE THREAD

**Issue by sunlianlong** [sunyongsheng/Allpass#4]
不知道是不是特例，特意借别人的Android手机体验了一下，发现导出csv后在电脑上看中文是乱码的；另外希望能有自动上传到网盘的功能(哪个网盘都可以)，之前用的密码管理工具带加密的，有一次遇到意外手机必须刷机，结果导致软件工具的密码没有了，网上的备份文件还是加密解不开

**Comment by sunyongsheng** [comment]
这个主要是因为Windows系统使用的编码方式和Android上不一样导致中文乱码，在Mac上使用 表格 打开可以正常显示，后续会考虑修复这个问题；目前最新版本（1.2.2）支持WebDAV同步，配置坚果云后就可以了，考虑到安全原因，所以上传到坚果云的文件还是密码部分是加密的，后续版本会添加 导出加密等级 的设置
