### ISSUE TITLE
刚学习，请教

### ISSUE THREAD

**Issue by ylmyg** [sunyongsheng/Allpass#5]
导入androidstudio报错The named parameter 'defPinyin' isn't defined.
不清楚怎么改。

**Comment by sunyongsheng** [comment]
在项目根目录下运行一下`flutter pub get`试试

**Comment by ylmyg** [comment]
运行了 还是这个错误 若要构建Allpass，请修改lib/utils/encrypt_util.dart中的_key（32位字符串） 而且和修改字符串也没有关系

**Comment by sunyongsheng** [comment]
> 运行了 还是这个错误 若要构建Allpass，请修改lib/utils/encrypt_util.dart中的_key（32位字符串） 而且和修改字符串也没有关系

看一下`pubspec.yaml`中`lpinyin`的版本是否是1.0.9，如果不是修改一下再运行一下`flutter pub get`，不要用`flutter pub upgrade`

**Comment by ylmyg** [comment]
就是1.0.9版本。是不是需要下载什么插件？

**Comment by sunyongsheng** [comment]
不需要，整个项目只有这一处报错吗

**Comment by ylmyg** [comment]
整个项目就是这里报错。

**Comment by sunyongsheng** [comment]
> 整个项目就是这里报错。

是password_provider还是card_provider？这两个文件中都有两处defPinyin，是全都报错吗

**Comment by ylmyg** [comment]
是的，这两处都是报错的。

**Comment by sunyongsheng** [comment]
> 是的，这两处都是报错的。

那看一下`PinyinHelper.getShortPinyin()`的函数声明，如果函数声明中有这个命名参数还报错的话就不清楚了

**Comment by ylmyg** [comment]
error: The named parameter 'defPinyin' isn't defined. (undefined_named_parameter at [allpass] lib\password\data\password_provider.dart:72)
error: The named parameter 'defPinyin' isn't defined. (undefined_named_parameter at [allpass] lib\card\data\card_provider.dart:46)
两次都是报错的

**Comment by ylmyg** [comment]
就是函数中的命名函数报错啊.....

**Comment by sunyongsheng** [comment]
> 就是函数中的命名函数报错啊.....

我知道但是这处只要lpinyin的版本没变就不可能有问题啊，你按住ctrl(command)，鼠标点击`getShortPinyin()`，跳进去看一下这个函数的声明是不是`static String getShortPinyin(String str, {String defPinyin = '#'})`，如果一模一样的话那只可能是你电脑上的AndroidStudio有问题，因为这个项目我在两台电脑三个系统上跑过都不会在这上面出现问题

**Comment by sunyongsheng** [comment]
尝试运行一下`flutter clean`并重启IDE
