### ISSUE TITLE
有个bug:关于懒加载的

### ISSUE THREAD

**Issue by SlotSun** [sunyongsheng/Allpass#7]
bug: webdav 无法登录

懒加载的实例（LazyImpl）本身需要被缓存，否则每次创建新的 LazyImpl 实例都会导致懒加载逻辑重新触发
每次访问 _requester 属性时都会创建一个新的 LazyImpl 对象，并立即访问其 value 属性。
因为 LazyImpl 是个新的实例，所以每次都会调用 _creator()，导致 WebDavRequester 多次被实例化

我的想法是注册成单例模式
![image](https://github.com/user-attachments/assets/b6afef4f-a115-4719-af70-0c5dab10e388)

**Comment by sunyongsheng** [comment]
你说的对，Lazy 对象本身需要被一个变量持有才行。WebDavRequester 本身只给 WebDavService 用，放在全局的 getIt 里感觉不太合适，我先简单处理一下
